server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  cloud:
    consul:
      host: 172.31.26.137
      port: 8500
      discovery:
        prefer-ip-address: true
        tags: version=1.0
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        healthCheckInterval: 15s
        health-check-timeout: 100s
        ip-address: ${spring.cloud.client.ip-address}

