server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: bfe8662580f52bfcbe6d
            client-secret: 1cce0033fadf002fa242a718d26012f03554b4fc

###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000
###配置请求超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            tim: 7000
    ###配置具体方法超时时间
    serverMethod:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
logging:
  config: classpath:logback-spring.xml
