server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  security:
    oauth2:
      client:
        registration:
          github:
            client_id: bfe8662580f52bfcbe6d
            client_secret: 1cce0033fadf002fa242a718d26012f03554b4fc
            accessTokenUri: https://github.com/login/oauth/access_token
            userAuthorizationUri: https://github.com/login/oauth/authorize
            user-info-uri: https://api.github.com/user
            clientAuthenticationMethod: post

mysql:
  server:
    ip: 47.104.150.14
    port: 3306
  db:
    name: paascloud_uac
  user:
    name: root
    password: 123456



mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml





