server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  datasource:
    url: jdbc:mysql://47.104.150.14:3306/paascloud_uac?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

logging:
  config: classpath:logback-spring.xml

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
  ### xxl-job executor address
    executor:
      appname: ${spring.application.name}
      ip: ${spring.cloud.client.ip-address}
      port: 9999

  ### xxl-job, access token
    accessToken:


